#!/sbin/sh
# @overview List all active patches
# @since 2018.03.13, 00:12
# @version 2018.03.13, 00:12

# Save source path
ORIGPATH=`pwd`

# Scan all `patch-config`s...
DIRS=`find_ . -name "patch-config.sh" \
  | sed 's/[\\]/\//g;s/\/[^\/]*$//g'`

# Process all found folders...
for D in $DIRS; do
  echo ""
  echo "$D:"
  find_ $D -name "*.diff"
done
