#!/sbin/sh
# @overview Patch utility script
# @since 2018.03.05, 00:00
# @version 2018.03.05, 00:22

# Save source path
ORIGPATH=`pwd`

# Scan all `patch-config`s...
DIRS=`find_ . -name "patch-config*" \
  | sed 's/[\\]/\//g;s/\/[^\/]*$//g'`

# Process all found folders...
for D in $DIRS; do
  echo ""
  echo "Processing $D..."
  cd "$D"
  sh "$ORIGPATH/patch-tool-apply"
  cd "$ORIGPATH"
done
