#!/sbin/sh
# @file ~/sbin/patch-tool
# @overview Patch utility script
# @since 2018.02.23, 23:35
# @version 2018.02.23, 23:35

# Loading configuration (PATCHCD etc)
. "patch-config.sh"

# Root path from config
echo "ROOTCD: $ROOTCD"

# Saving source path
SRCPATH=`pwd`
echo "SRCPATH: $SRCPATH"

# Finding diffs...
DIFFS=`find_ . -name "*.diff"`
echo "DIFFS: $DIFFS"

# Maximum scanning path depth
MAXDEPTH=15

# Patching root (finding this folder in parents recursively).
FOUNDROOT=""
L=1
while [ $L -le $MAXDEPTH ]; do
    echo -n "."
    if [ -d "$ROOTCD" ]; then
        echo " Found root: $ROOTCD"
        FOUNDROOT=1
        break
    fi
    ROOTCD="../$ROOTCD"
    L=$(expr $L + 1)
done
# If no root found...
if [ -z "${FOUNDROOT}" ]; then
    echo " No project root found!"
    exit
fi

WORKPATH="$ROOTCD/$PATCHCD"
if [ ! -d "$WORKPATH" ]; then
  echo "No working path ($WORKPATH) exists!"
  exit 1
fi

# Cd to working path
echo "Working in $WORKPATH"
cd "$WORKPATH"

# Patching file
for NAME in $DIFFS; do
  echo ""
  echo "Patching with $NAME ..."
  cp -vf "$SRCPATH/$NAME" .
  patch -lb --verbose < "$NAME"
done

# Returning path to original path
cd $SRCPATH

